# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directories: # Location of package manifests 
      - "/Beginners/Crypto2/src/"
      - "/Experts/Crypto2/src/"
    schedule:
      interval: "weekly"
    labels:
      - "pip dependencies"
      
  - package-ecosystem: "npm" # See documentation for possible values
    directories: # Location of package manifests 
      - "/Beginners/Web2/src/"
      - "/Beginners/Web3/src/"
    schedule:
      interval: "weekly"
    labels:
      - "npm dependencies"